### ISSUE TITLE
csproj: set container limits

### ISSUE THREAD

**Issue by tmds** [tmds/dotnet-shift#63]
## Spec

```xml
<ContainerCpuRequest/>
<ContainerCpuLimit/>
<ContainerMemoryRequest/>
<ContainerMemoryLimit/>
```

These control the the `resources` on the .NET app container:

```yaml
resources:
  requests:
    memory: "ContainerMemoryRequest"
    cpu: "ContainerCpuRequest"
  limits:
    memory: "ContainerMemoryLimit"
    cpu: "ContainerCpuLimit"
```
