### ISSUE TITLE
csproj: persistent storage

### ISSUE THREAD

**Issue by tmds** [tmds/dotnet-shift#65]
## Spec

```xml
<ContainerPersistentStorage Include="data"
                            Size="8Gi"
                            Path="/data"

		            Limit=""
                            StorageClass=""
                            Access="ReadWriteMany"/>
```
The attributes after the empty line are optional, and show their default value.

Generates a corresponding PVC:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{name}}-{{Include}}
spec:
  accessModes:
    - {{Access}}
  resources:
    requests:
      storage: {{Size}}
    limits:
      storage: {{Limit}}
  storageClassName: {{StorageClass}}
```

This volume is mounted in the application container at `{{Path}}`.
